name: e2e
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=41.0.3=py310hdda0065_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.3.52=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.3.52=0
  - cuda-nsight-compute=12.3.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.3.52=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.3.52=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.3.52=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.3.52=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.8.0.34=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_core=4.12.0=py310hff52083_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.8.0.34=0
  - libcufile-dev=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcurand-dev=10.3.4.52=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2023.3.0.12=0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.11=h7f8727e_2
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3=py310h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py310_cu116
  - torchvision=0.14.1=py310_cu116
  - traitlets=5.13.0=pyhd8ed1ab_0
  - urllib3=1.26.18=py310h06a4308_0
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - annotated-types==0.7.0
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - click==8.2.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - d2l==1.0.3
    - defusedxml==0.7.1
    - dnspython==2.7.0
    - email-validator==2.3.0
    - fastapi==0.116.1
    - fastapi-cli==0.0.10
    - fastapi-cloud-cli==0.1.5
    - fastjsonschema==2.18.1
    - fonttools==4.44.0
    - fqdn==1.5.1
    - h11==0.16.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - iniconfig==2.0.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jinja2==3.1.6
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.2
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.5.0
    - jupyter-console==6.6.3
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.9.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - lxml==4.9.3
    - markdown-it-py==4.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - mistune==3.0.2
    - nbclient==0.8.0
    - nbconvert==7.10.0
    - nbformat==5.9.2
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numpy==1.23.5
    - nvidia-ml-py==12.575.51
    - overrides==7.4.0
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - pluggy==1.3.0
    - prometheus-client==0.18.0
    - pybind11==2.11.1
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pymap3d==3.1.0
    - pynvml==12.0.0
    - pyparsing==3.0.9
    - pyrtklib==0.2.7
    - pytest==7.4.3
    - python-dotenv==1.1.1
    - python-graphviz==0.20.3
    - python-json-logger==2.0.7
    - python-multipart==0.0.20
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - qtconsole==5.4.4
    - qtpy==2.4.1
    - referencing==0.30.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==14.1.0
    - rich-toolkit==0.15.1
    - rignore==0.6.4
    - rpds-py==0.10.6
    - scikit-sparse==0.4.12
    - scipy==1.10.1
    - semantic-version==2.10.0
    - send2trash==1.8.2
    - sentry-sdk==2.37.0
    - shellingham==1.5.4
    - sniffio==1.3.0
    - soupsieve==2.5
    - starlette==0.47.3
    - terminado==0.17.1
    - theseus-ai==0.2.1
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torchkin==0.1.1
    - torchlie==0.1.0
    - torchviz==0.0.2
    - tornado==6.3.3
    - tqdm==4.66.1
    - typer==0.17.3
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.15.0
    - typing-inspection==0.4.1
    - tzdata==2023.3
    - urdf-parser-py==0.0.4
    - uri-template==1.3.0
    - uvicorn==0.35.0
    - uvloop==0.21.0
    - watchfiles==1.1.0
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - websockets==15.0.1
    - widgetsnbextension==4.0.9
prefix: /home/ling/miniconda3/envs/e2e
